import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../../../shared/models/attendance_record.dart';
import '../../../../shared/models/school_class.dart';
import '../../../../shared/models/student.dart';
import '../../../../shared/services/attendance_service.dart';
import '../../../../shared/services/student_service.dart';
import '../teacher_dashboard_screen.dart';

// Provider to stream students of the teacher's class
final teacherClassStudentsProvider = StreamProvider<List<Student>>((ref) {
  final classAsync = ref.watch(teacherClassProvider);
  if (classAsync.value == null) return const Stream.empty();
  final schoolClass = classAsync.value!;
  return ref.read(studentServiceProvider).getStudentsByClass(schoolClass.schoolId, schoolClass.classId);
});

// StateProvider for the currently selected date in the attendance tab
final attendanceDateProvider = StateProvider<DateTime>((ref) => DateTime.now());

// FutureProvider to fetch attendance records for the selected date
final attendanceRecordsProvider = FutureProvider<List<AttendanceRecord>>((ref) async {
  final classAsync = ref.watch(teacherClassProvider);
  final date = ref.watch(attendanceDateProvider);
  
  if (classAsync.value == null) return [];
  final schoolClass = classAsync.value!;
  
  final dateStr = DateFormat('yyyy-MM-dd').format(date);
  return ref.read(attendanceServiceProvider).getAttendanceByDate(
    schoolClass.schoolId, 
    schoolClass.classId, 
    dateStr,
  );
});

class AttendanceTab extends ConsumerStatefulWidget {
  const AttendanceTab({super.key});

  @override
  ConsumerState<AttendanceTab> createState() => _AttendanceTabState();
}

class _AttendanceTabState extends ConsumerState<AttendanceTab> {
  // Local state to hold modifications before submission
  final Map<String, AttendanceStatus> _localStatuses = {};
  bool _isEditing = false;

  @override
  void initState() {
    super.initState();
  }

  void _syncWithFetchedRecords(List<AttendanceRecord> records) {
    if (!_isEditing && _localStatuses.isEmpty) {
      for (var record in records) {
        _localStatuses[record.studentId] = record.status;
      }
    }
  }

  void _markAllPresent(List<Student> students) {
    setState(() {
      for (var student in students) {
        _localStatuses[student.studentId] = AttendanceStatus.present;
      }
      _isEditing = true;
    });
  }

  Future<void> _submitAttendance(SchoolClass schoolClass, DateTime date) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    final dateStr = DateFormat('yyyy-MM-dd').format(date);
    
    final recordsToSave = _localStatuses.entries.map((entry) {
      return AttendanceRecord(
        recordId: '', // Will be generated by service if empty, though we ideally want to reuse existing if any
        studentId: entry.key,
        classId: schoolClass.classId,
        schoolId: schoolClass.schoolId,
        date: dateStr,
        status: entry.value,
        markedByUid: user.uid,
        timestamp: Timestamp.now(),
      );
    }).toList();

    try {
      await ref.read(attendanceServiceProvider).markAttendance(recordsToSave);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Attendance submitted successfully!')),
        );
        setState(() {
          _isEditing = false;
        });
        // Invalidate to refresh fetched records
        ref.invalidate(attendanceRecordsProvider);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final selectedDate = ref.watch(attendanceDateProvider);
    final studentsAsync = ref.watch(teacherClassStudentsProvider);
    final recordsAsync = ref.watch(attendanceRecordsProvider);
    final classAsync = ref.watch(teacherClassProvider);

    // Sync fetched records to local state if empty
    recordsAsync.whenData((records) {
      if (!_isEditing && _localStatuses.isEmpty && records.isNotEmpty) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (mounted) {
            setState(() {
              _syncWithFetchedRecords(records);
            });
          }
        });
      }
    });

    final isToday = DateFormat('yyyy-MM-dd').format(selectedDate) == DateFormat('yyyy-MM-dd').format(DateTime.now());
    final isSubmitted = recordsAsync.value?.isNotEmpty ?? false;

    return Scaffold(
      backgroundColor: theme.colorScheme.surfaceContainerLowest,
      body: Column(
        children: [
          _buildDateHeader(context, selectedDate, isToday),
          _buildSummaryStrip(context, studentsAsync.value ?? []),
          if (isToday && _localStatuses.isEmpty && !isSubmitted)
            _buildBulkAction(context, studentsAsync.value ?? []),
          Expanded(
            child: studentsAsync.when(
              data: (students) {
                if (students.isEmpty) {
                  return const Center(child: Text('No students in this class.'));
                }
                return ListView.separated(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  itemCount: students.length,
                  separatorBuilder: (_, __) => const SizedBox(height: 8),
                  itemBuilder: (context, index) {
                    final student = students[index];
                    return _buildStudentRow(context, student);
                  },
                );
              },
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, _) => Center(child: Text('Error: $e')),
            ),
          ),
          _buildSubmitSection(context, classAsync.value, selectedDate, isSubmitted),
        ],
      ),
    );
  }

  Widget _buildDateHeader(BuildContext context, DateTime selectedDate, bool isToday) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      color: theme.colorScheme.surface,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            icon: const Icon(Icons.chevron_left_rounded),
            onPressed: () {
              ref.read(attendanceDateProvider.notifier).state = selectedDate.subtract(const Duration(days: 1));
              setState(() {
                _localStatuses.clear();
                _isEditing = false;
              });
            },
          ),
          Column(
            children: [
              Text(
                DateFormat('EEEE').format(selectedDate),
                style: theme.textTheme.bodyMedium?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              Text(
                DateFormat('d MMMM yyyy').format(selectedDate),
                style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
            ],
          ),
          IconButton(
            icon: const Icon(Icons.chevron_right_rounded),
            onPressed: isToday
                ? null
                : () {
                    ref.read(attendanceDateProvider.notifier).state = selectedDate.add(const Duration(days: 1));
                    setState(() {
                      _localStatuses.clear();
                      _isEditing = false;
                    });
                  },
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryStrip(BuildContext context, List<Student> students) {
    int present = 0;
    int absent = 0;
    int late = 0;
    
    for (var status in _localStatuses.values) {
      if (status == AttendanceStatus.present) present++;
      if (status == AttendanceStatus.absent) absent++;
      if (status == AttendanceStatus.late) late++;
    }
    
    int unmarked = students.length - (present + absent + late);

    return Container(
      padding: const EdgeInsets.symmetric(vertical: 12),
      color: Theme.of(context).colorScheme.surfaceContainerHighest.withAlpha(100),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          _buildSummaryItem('Present', present, Colors.green),
          _buildSummaryItem('Absent', absent, Colors.red),
          _buildSummaryItem('Late', late, Colors.orange),
          _buildSummaryItem('Unmarked', unmarked, Colors.grey),
        ],
      ),
    );
  }

  Widget _buildSummaryItem(String label, int count, Color color) {
    return Column(
      children: [
        Text(count.toString(), style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: color)),
        Text(label, style: const TextStyle(fontSize: 12)),
      ],
    );
  }

  Widget _buildBulkAction(BuildContext context, List<Student> students) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8),
      child: SizedBox(
        width: double.infinity,
        child: OutlinedButton.icon(
          onPressed: () => _markAllPresent(students),
          icon: const Icon(Icons.done_all_rounded, color: Colors.green),
          label: const Text('Mark All Present'),
          style: OutlinedButton.styleFrom(
            foregroundColor: Colors.green,
            side: const BorderSide(color: Colors.green),
          ),
        ),
      ),
    );
  }

  Widget _buildStudentRow(BuildContext context, Student student) {
    final theme = Theme.of(context);
    final status = _localStatuses[student.studentId];

    return Card(
      elevation: 0,
      color: theme.colorScheme.surfaceContainer,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        child: Column(
          children: [
            Row(
              children: [
                CircleAvatar(
                  backgroundColor: theme.colorScheme.primaryContainer,
                  child: Text(student.name.substring(0, 1)),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    student.name,
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.edit_note_rounded),
                  color: theme.colorScheme.primary,
                  onPressed: () {
                    // Add note modal
                  },
                )
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: SegmentedButton<AttendanceStatus>(
                    segments: const [
                      ButtonSegment(value: AttendanceStatus.present, label: Text('Present')),
                      ButtonSegment(value: AttendanceStatus.late, label: Text('Late')),
                      ButtonSegment(value: AttendanceStatus.absent, label: Text('Absent')),
                    ],
                    selected: status != null ? {status} : <AttendanceStatus>{},
                    onSelectionChanged: (Set<AttendanceStatus> newSelection) {
                      setState(() {
                        _localStatuses[student.studentId] = newSelection.first;
                        _isEditing = true;
                      });
                    },
                    style: SegmentedButton.styleFrom(
                      selectedBackgroundColor: status == AttendanceStatus.present
                          ? Colors.green.withAlpha(50)
                          : status == AttendanceStatus.absent
                              ? Colors.red.withAlpha(50)
                              : status == AttendanceStatus.late
                                  ? Colors.orange.withAlpha(50)
                                  : null,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSubmitSection(BuildContext context, SchoolClass? schoolClass, DateTime date, bool isSubmitted) {
    final theme = Theme.of(context);
    
    if (schoolClass == null) return const SizedBox.shrink();

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(10),
            blurRadius: 10,
            offset: const Offset(0, -5),
          )
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (isSubmitted && !_isEditing) ...[
            Text(
              'Submitted at 9:14 AM by Ms. Sharma', // Mock text
              textAlign: TextAlign.center,
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
            ),
            const SizedBox(height: 8),
            ElevatedButton.icon(
              onPressed: () {
                setState(() {
                  _isEditing = true;
                });
              },
              icon: const Icon(Icons.edit_rounded),
              label: const Text('Edit Attendance'),
              style: ElevatedButton.styleFrom(
                backgroundColor: theme.colorScheme.secondaryContainer,
                foregroundColor: theme.colorScheme.onSecondaryContainer,
                padding: const EdgeInsets.symmetric(vertical: 16),
              ),
            ),
          ] else ...[
            ElevatedButton(
              onPressed: _localStatuses.isEmpty ? null : () => _submitAttendance(schoolClass, date),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
                backgroundColor: theme.colorScheme.primary,
                foregroundColor: theme.colorScheme.onPrimary,
              ),
              child: const Text('Submit Attendance', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            ),
          ]
        ],
      ),
    );
  }
}
