// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVaIqKvnfC2z-DWjGenCFlKBTP1_DfxI',
    appId: '1:456710793829:web:4b9a8c2f75c15a4f60348c',
    messagingSenderId: '456710793829',
    projectId: 'preschool-hub-01',
    authDomain: 'preschool-hub-01.firebaseapp.com',
    storageBucket: 'preschool-hub-01.firebasestorage.app',
    measurementId: 'G-EB1XB3YC2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGi0tA-iekNQT9Y3Ckn1iSZms7BLtrgQ0',
    appId: '1:456710793829:android:48d5acf88a2f323560348c',
    messagingSenderId: '456710793829',
    projectId: 'preschool-hub-01',
    storageBucket: 'preschool-hub-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBPPzxyNWRS2u_VANugfNRxL5tVVtXUg',
    appId: '1:456710793829:ios:e89dc1be30fe2ea860348c',
    messagingSenderId: '456710793829',
    projectId: 'preschool-hub-01',
    storageBucket: 'preschool-hub-01.firebasestorage.app',
    iosBundleId: 'com.example.preschoolHub',
  );
}
